### ISSUE TITLE
[1.12.2] Crash when punching Evolved Enderman from p455w0rd's Evolved Enderman mod

### ISSUE THREAD

**Issue by CobaltRealm** [Insane-96/VulcaniteMod#2]
Every time I hit an Evolved Enderman my game crashes, I submited it in the Evolved Enderman Github but p455w0rd says that its your mod that causes the crash. I putted all the crash report because I dont know whats the part that you need for solving the problem

Thanks

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  LoadingPlugin (Quark-r1.4-121.jar)
  ColytraLoadingPlugin (colytra-1.12.2-1.0.4.3.jar)
  IELoadingPlugin (ImmersiveEngineering-0.12-76-core.jar)
  Worldgeneration Profiler Plugin (worldgenerationprofiler-v1.1.1.jar)
  IMLoadingPlugin (infinimend-1.12-1.0.2.jar)
  NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  FMLPlugin (elulib-0.1.11.jar)
  CoreMod (Aroma1997Core-1.12.2-1.3.0.2.jar)
  ForgelinPlugin (Forgelin-1.6.0.jar)
  ComfortsCoreLoadingPlugin (comforts-1.12.2-1.1.0.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  LoadingPlugin (noRecipeBookv1.0.0_formc1.12.2.jar)
Contact their authors BEFORE contacting forge

// On the bright side, I bought you a teddy bear!

Time: 1/20/18 1:52 PM
Description: Unexpected error

java.lang.ClassCastException: net.minecraft.client.entity.EntityPlayerSP cannot be cast to net.minecraft.entity.player.EntityPlayerMP
	at net.insane96mcp.vulcanite.events.LivingHurt.OnPlayerDamageEntity(LivingHurt.java:80)
	at net.insane96mcp.vulcanite.events.LivingHurt.LivingHurtEvent(LivingHurt.java:22)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1748_LivingHurt_LivingHurtEvent_LivingHurtEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:574)
	at net.minecraft.entity.EntityLivingBase.func_70665_d(EntityLivingBase.java:1401)
	at p455w0rd.endermanevo.entity.EntityEvolvedEnderman.func_70097_a(EntityEvolvedEnderman.java:183)
	at slimeknights.tconstruct.library.tools.ToolCore.dealDamage(ToolCore.java:149)
	at slimeknights.tconstruct.library.utils.ToolHelper.attackEntity(ToolHelper.java:726)
	at slimeknights.tconstruct.library.utils.ToolHelper.attackEntity(ToolHelper.java:611)
	at slimeknights.tconstruct.library.utils.ToolHelper.attackEntity(ToolHelper.java:607)
	at slimeknights.tconstruct.library.tools.ToolCore.onLeftClickEntity(ToolCore.java:237)
	at net.minecraftforge.common.ForgeHooks.onPlayerAttackTarget(ForgeHooks.java:1040)
	at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1250)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78764_a(PlayerControllerMP.java:540)
	at net.minecraft.client.Minecraft.func_147116_af(Minecraft.java:1509)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2247)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2018)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1806)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.insane96mcp.vulcanite.events.LivingHurt.OnPlayerDamageEntity(LivingHurt.java:80)
	at net.insane96mcp.vulcanite.events.LivingHurt.LivingHurtEvent(LivingHurt.java:22)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1748_LivingHurt_LivingHurtEvent_LivingHurtEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:574)
	at net.minecraft.entity.EntityLivingBase.func_70665_d(EntityLivingBase.java:1401)
	at p455w0rd.endermanevo.entity.EntityEvolvedEnderman.func_70097_a(EntityEvolvedEnderman.java:183)
	at slimeknights.tconstruct.library.tools.ToolCore.dealDamage(ToolCore.java:149)
	at slimeknights.tconstruct.library.utils.ToolHelper.attackEntity(ToolHelper.java:726)
	at slimeknights.tconstruct.library.utils.ToolHelper.attackEntity(ToolHelper.java:611)
	at slimeknights.tconstruct.library.utils.ToolHelper.attackEntity(ToolHelper.java:607)
	at slimeknights.tconstruct.library.tools.ToolCore.onLeftClickEntity(ToolCore.java:237)
	at net.minecraftforge.common.ForgeHooks.onPlayerAttackTarget(ForgeHooks.java:1040)
	at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1250)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78764_a(PlayerControllerMP.java:540)
	at net.minecraft.client.Minecraft.func_147116_af(Minecraft.java:1509)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2247)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2018)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Ancient_Cobalt'/328, l='MpServer', x=1039.90, y=67.00, z=-3870.40]]
	Chunk stats: MultiplayerChunkCache: 225, 225
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (248,64,248), Chunk: (at 8,4,8 in 15,15; contains blocks 240,0,240 to 255,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 3504992 game time, 3645113 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 79 total; [EntityWitch['Witch'/6151, l='MpServer', x=1035.73, y=48.00, z=-3891.51], EntityItem['item.item.actuallyadditions.item_solidified_experience'/29225, l='MpServer', x=983.80, y=64.00, z=-3890.72], EntityItem['item.item.rabbitHide'/28217, l='MpServer', x=1000.77, y=63.00, z=-3852.43], EntityDeer['Deer'/28233, l='MpServer', x=999.79, y=64.00, z=-3887.79], EntityVillager['Villager'/29276, l='MpServer', x=1106.51, y=64.00, z=-3815.30], EntityVillager['Villager'/29277, l='MpServer', x=1106.51, y=64.00, z=-3815.70], EntityZombie['Zombie'/28254, l='MpServer', x=1018.85, y=64.00, z=-3879.35], EntityVillager['Villager'/29278, l='MpServer', x=1118.38, y=64.00, z=-3816.50], EntityVillager['Villager'/29279, l='MpServer', x=1117.35, y=64.00, z=-3812.50], EntityStray['Stray'/28256, l='MpServer', x=1013.50, y=68.00, z=-3806.50], EntityVillager['Villager'/29280, l='MpServer', x=1117.44, y=64.00, z=-3802.86], EntityStray['Stray'/28262, l='MpServer', x=1006.75, y=69.00, z=-3809.47], EntityEvolvedEnderman['Evolved Enderman'/28263, l='MpServer', x=1038.34, y=67.37, z=-3870.43], EntityVillager['Villager'/29287, l='MpServer', x=1111.73, y=65.00, z=-3828.50], EntityBat['Bat'/28267, l='MpServer', x=1074.36, y=29.00, z=-3817.81], EntitySquid['Squid'/27266, l='MpServer', x=1054.32, y=58.02, z=-3819.78], EntitySquid['Squid'/27267, l='MpServer', x=1046.94, y=55.65, z=-3822.18], EntityScent['entity.EntityScent.name'/28811, l='MpServer', x=1014.90, y=63.00, z=-3874.12], EntityItem['item.item.muttonRaw'/29334, l='MpServer', x=982.17, y=64.00, z=-3890.20], EntitySquid['Squid'/27286, l='MpServer', x=1057.47, y=59.88, z=-3809.94], EntityZombie['Zombie'/28312, l='MpServer', x=1010.16, y=63.00, z=-3871.45], EntitySpider['Spider'/28314, l='MpServer', x=1004.07, y=65.00, z=-3894.11], EntityCreeper['Creeper'/28315, l='MpServer', x=1029.14, y=72.00, z=-3927.31], EntityItem['item.tile.cloth.black'/29340, l='MpServer', x=981.98, y=64.00, z=-3890.19], EntityItem['item.item.potion'/29344, l='MpServer', x=982.06, y=64.00, z=-3890.21], EntitySpider['Spider'/28322, l='MpServer', x=1010.46, y=64.00, z=-3888.37], EntityScent['entity.EntityScent.name'/28838, l='MpServer', x=1014.25, y=63.00, z=-3869.80], EntityStray['Stray'/28330, l='MpServer', x=994.70, y=64.00, z=-3883.52], EntityEvolvedEnderman['Evolved Enderman'/28349, l='MpServer', x=1068.36, y=67.00, z=-3856.70], EntityEvolvedEnderman['Evolved Enderman'/28350, l='MpServer', x=1077.50, y=67.00, z=-3853.19], EntitySpider['Spider'/28353, l='MpServer', x=1022.05, y=65.46, z=-3893.89], EntitySpider['Spider'/28354, l='MpServer', x=1029.48, y=65.70, z=-3875.03], EntityScent['entity.EntityScent.name'/29391, l='MpServer', x=1033.68, y=66.00, z=-3872.36], EntityZombie['Zombie'/28370, l='MpServer', x=1005.41, y=64.00, z=-3876.05], EntityCreeper['Creeper'/28376, l='MpServer', x=1044.50, y=64.00, z=-3893.50], EntitySpider['Spider'/28377, l='MpServer', x=1034.50, y=73.00, z=-3940.50], EntityScent['entity.EntityScent.name'/29401, l='MpServer', x=1035.58, y=66.00, z=-3871.65], EntityItem['item.item.snowball'/28897, l='MpServer', x=1011.46, y=63.00, z=-3870.49], EntityCreeper['Creeper'/28386, l='MpServer', x=1017.18, y=67.00, z=-3899.56], EntityItem['item.item.red_heart'/28898, l='MpServer', x=1009.77, y=64.00, z=-3869.89], EntityCreeper['Creeper'/28387, l='MpServer', x=1062.50, y=71.00, z=-3916.50], EntityItem['item.item.actuallyadditions.item_solidified_experience'/28899, l='MpServer', x=1009.44, y=64.00, z=-3870.02], EntityStray['Stray'/28391, l='MpServer', x=980.67, y=64.00, z=-3881.48], EntityZombie['Zombie'/28392, l='MpServer', x=1012.21, y=64.00, z=-3877.75], EntityStray['Stray'/28394, l='MpServer', x=1000.50, y=64.00, z=-3929.50], EntitySpider['Spider'/28395, l='MpServer', x=1039.79, y=66.00, z=-3863.89], EntityCreeper['Creeper'/28399, l='MpServer', x=969.87, y=64.00, z=-3891.13], EntityZombie['Zombie'/28403, l='MpServer', x=993.17, y=66.00, z=-3828.50], EntityZombieVillager['Zombie Villager'/28404, l='MpServer', x=1036.50, y=68.00, z=-3835.50], EntityCreeper['Creeper'/28408, l='MpServer', x=975.50, y=64.00, z=-3886.50], EntityCreeper['Creeper'/28409, l='MpServer', x=980.35, y=64.00, z=-3892.19], EntityCreeper['Creeper'/28410, l='MpServer', x=978.50, y=64.00, z=-3891.50], EntityItem['item.item.actuallyadditions.item_food_rice'/24322, l='MpServer', x=1064.47, y=60.00, z=-3830.84], EntityItem['item.item.actuallyadditions.item_rice_seed'/24323, l='MpServer', x=1066.56, y=63.00, z=-3831.88], EntityScent['entity.EntityScent.name'/28941, l='MpServer', x=1011.73, y=63.00, z=-3869.82], EntityCreeper['Creeper'/27411, l='MpServer', x=1053.50, y=71.00, z=-3920.50], EntityScent['entity.EntityScent.name'/28947, l='MpServer', x=1010.25, y=64.00, z=-3869.88], EntityScent['entity.EntityScent.name'/28955, l='MpServer', x=1010.14, y=65.96, z=-3869.38], EntityRabbit['Rabbit'/27434, l='MpServer', x=961.62, y=64.00, z=-3886.71], EntityItemFrame['entity.ItemFrame.name'/28972, l='MpServer', x=1133.97, y=67.50, z=-3828.50], EntityBat['Bat'/27437, l='MpServer', x=1011.19, y=33.21, z=-3866.70], EntityScent['entity.EntityScent.name'/28489, l='MpServer', x=1049.42, y=64.72, z=-3883.41], EntityPlayerSP['Ancient_Cobalt'/328, l='MpServer', x=1039.90, y=67.00, z=-3870.40], EntityScent['entity.EntityScent.name'/28505, l='MpServer', x=1046.33, y=64.00, z=-3885.79], EntityStray['Stray'/26986, l='MpServer', x=1012.50, y=68.00, z=-3802.50], EntityRabbit['Rabbit'/20348, l='MpServer', x=1028.69, y=70.00, z=-3912.52], EntityStray['Stray'/28542, l='MpServer', x=990.67, y=64.00, z=-3900.27], EntityDeer['Deer'/27534, l='MpServer', x=977.16, y=64.00, z=-3900.28], EntityItem['item.item.actuallyadditions.item_rice_seed'/27545, l='MpServer', x=987.71, y=64.00, z=-3861.14], EntityFluidCow['Fluid Cow'/27550, l='MpServer', x=988.88, y=63.00, z=-3811.27], EntityItem['item.tile.cloth.black'/29088, l='MpServer', x=987.80, y=64.00, z=-3890.44], EntityItem['item.item.potion'/29089, l='MpServer', x=988.02, y=64.00, z=-3892.51], EntityRabbit['Rabbit'/25037, l='MpServer', x=1026.02, y=64.57, z=-3888.21], EntityRabbit['Rabbit'/25038, l='MpServer', x=1026.52, y=71.00, z=-3919.67], EntityKomodo['Komodo'/5606, l='MpServer', x=586.50, y=74.00, z=-792.50], EntityItem['item.tile.oreshrubs:oreshrub_random'/29158, l='MpServer', x=987.00, y=64.00, z=-3891.47], EntityRabbit['Rabbit'/26614, l='MpServer', x=1096.31, y=64.00, z=-3816.61], EntityWitherSkeleton['Wither Skeleton'/28662, l='MpServer', x=973.50, y=68.00, z=-3790.50], EntityRabbit['Rabbit'/26615, l='MpServer', x=1086.77, y=63.00, z=-3806.75]]
	Retry entities: 1 total; [EntityKomodo['Komodo'/5606, l='MpServer', x=586.50, y=74.00, z=-792.50]]
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2748)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:426)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 996087696 bytes (949 MB) / 5110235136 bytes (4873 MB) up to 5249695744 bytes (5006 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5632m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.1.2590 Optifine OptiFine_1.12.2_HD_U_C8 239 mods loaded, 239 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

**Comment by Insane96** [comment]
Thanks for reporting. Will fix
